// Domain-control keys: one per name, random, and NOT a Nostr identity.
//
// THE INVARIANT (as for the mail key): the private key is generated here, in
// the user's own process, and goes to exactly one place — the vault. Nothing
// in this directory puts private key material into a network request; a claim
// sends the PUBLIC key and signatures, nothing else.
//
// WHY ONE KEY PER NAME (Matt, 2026-08-20 — this is load-bearing, not
// hygiene). The per-name secret IS the capability: handing someone the key
// for `shop.wildroot` delegates control of that domain to them, and nothing
// else. Names must therefore never share a key, and there must be no master
// secret that derives them all — a phrase that regenerated every key would
// turn "here, run my shop" into "here, take everything".
//
// WHY THERE IS NO RECOVERY PHRASE (Matt, same day: "I don't want a phrase").
// Twelve words in front of a first-run screen is where adoption dies, and a
// phrase written down by nobody protects nothing. Keys are random, they live
// in the vault, and backup is a file the user exports when they care — see
// identity-account.js. The honest cost is stated there: nothing is
// recoverable from memory, so the backup nudge has to be real.
//
// WHY IT IS NOT THE USER'S NOSTR KEY (Matt: "slightly different because it
// has a different purpose"). Key separation is the point: a delegate who can
// run your domain must not thereby be able to post as you. Everything about
// the CRYPTOGRAPHY and the ENCODING is deliberately identical to Nostr's —
// BIP-340 over secp256k1, NIP-01 signed events, NIP-19 npub/nsec — so every
// existing tool can verify and carry these keys (Matt: "the encoding can be
// the same, just maybe a different record name"). What differs is WHICH key
// and WHERE it is published: control keys live at `_hns.<name>` (record.js),
// and a social identity, when the user has one, is a different key at
// `_nostr.<name>`.

import { randomBytes } from 'node:crypto'
import { schnorr } from '@noble/curves/secp256k1'

/** Names the scheme in stored rows, so a future v2 can coexist. */
export const DERIVATION = 'hns-control-v1'

const HEX_64 = /^[0-9a-f]{64}$/

/** The secp256k1 group order; a secret key must be in [1, N). */
const CURVE_N = 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141n

/**
 * Normalize a name to the exact form every signed object uses: lowercase
 * FQDN, no trailing dot, LDH labels, at least two labels (an SLD under a
 * TLD — a bare TLD is not a Wildroot identity). Throws rather than guessing.
 */
export function normalizeName (name) {
  if (typeof name !== 'string') throw new Error('name must be a string')
  const cleaned = name.trim().toLowerCase().replace(/\.$/, '')
  const labels = cleaned.split('.')
  if (labels.length < 2) {
    throw new Error(`not an SLD: "${cleaned}" (need label.tld)`)
  }
  for (const label of labels) {
    if (!/^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/.test(label) || label.length > 63) {
      throw new Error(`invalid label "${label}" in "${cleaned}"`)
    }
  }
  return cleaned
}

function bytesToBigInt (bytes) {
  let n = 0n
  for (const b of bytes) n = (n << 8n) | BigInt(b)
  return n
}

/** A fresh control key from the OS CSPRNG. */
export function generateControlKey () {
  for (;;) {
    const secret = randomBytes(32)
    const scalar = bytesToBigInt(secret)
    // Out-of-range is a ~2^-128 event; the check exists so the code has an
    // answer rather than producing a key that cannot sign.
    if (scalar < 1n || scalar >= CURVE_N) continue
    return {
      secretKey: secret,
      publicKey: Buffer.from(schnorr.getPublicKey(secret)).toString('hex')
    }
  }
}

/**
 * Rebuild a control key from a secret someone holds — importing your own
 * backup, or RECEIVING a delegation. Those are the same operation, which is
 * why there is one function for both.
 */
/**
 * The purpose keys a newly issued name gets, generated with it.
 *
 * `control` is NOT in here: it is generated separately and proved by the
 * claim receipt. These are the keys that make the name immediately USABLE —
 * a social identity to post with, an authority for its DNS, a credential for
 * its mailbox — and they exist because asking a new user to come back later
 * and "enable" each service is the friction that loses them.
 *
 * Each is independent randomness, not a derivation of the control key. That
 * is the same rule as one-random-key-per-name and for the same reason: the
 * control key is meant to be handed over, and anything derivable from it
 * would be handed over with it.
 *
 * PGP is absent on purpose — it is a different algorithm with a different
 * lifecycle, generated by the one-click mail-encryption step and bound to the
 * name afterwards.
 */
export const PURPOSE_KEYS = ['nostr', 'dns', 'mail']

export function generatePurposeKeys (purposes = PURPOSE_KEYS) {
  const out = {}
  for (const purpose of purposes) out[purpose] = generateControlKey()
  return out
}

export function controlKeyFromSecret (secret) {
  const bytes = Buffer.isBuffer(secret)
    ? secret
    : Buffer.from(String(secret).replace(/^0x/, ''), 'hex')
  if (bytes.length !== 32) throw new Error('a control key is 32 bytes')
  const scalar = bytesToBigInt(bytes)
  if (scalar < 1n || scalar >= CURVE_N) throw new Error('not a valid secp256k1 key')
  return {
    secretKey: bytes,
    publicKey: Buffer.from(schnorr.getPublicKey(bytes)).toString('hex')
  }
}

/** Is this a well-formed x-only public key string? (Format check only.) */
export function isPublicKeyHex (value) {
  return typeof value === 'string' && HEX_64.test(value)
}
