// The roots a CAR file CLAIMS, read from its own header.
//
// This is the check that closes the `car=` stated-origin loop (SPEC §6): the
// archive fetched from the origin a name states must be an archive *of the CID
// the name points at*, and the header is where an archive says which root it
// carries. Read this together with SPEC §11.2 — the claim is a sanity
// check, and the security comes from somewhere else.
//
// Lifted from `src/hns/ipfs.js` in the Wildroot tree, where `IPFSNode.importCar`
// calls it before handing the file to the daemon.
//
// ONE EXTRACTION DEVIATION, and it is in the decoder, so it is stated here and
// again in ../../DEVIATIONS.md IP-7. The Wildroot copy decodes the header with
// `@ipld/dag-cbor`. That package is not a dependency of this one, so the
// header — a fixed, tiny shape defined by the CAR specification — is decoded
// by `decodeHeaderCbor` below instead. It reads the CBOR subset dag-cbor can
// produce for this structure (unsigned integers, byte strings, text strings,
// arrays, maps and tag 42) and refuses everything else, including the
// indefinite-length forms dag-cbor forbids. It does NOT check dag-cbor's
// canonical map ordering, which `@ipld/dag-cbor` also does not enforce on
// decode. `tests/car-roots.test.js` pins it against header bytes generated by
// the real `@ipld/dag-cbor` encoder.

import fs from 'node:fs'
import { CID } from 'multiformats/cid'

/**
 * The roots named in a CARv1 header: a varint length, then a dag-cbor map
 * `{ version: 1, roots: [CID…] }` (CAR spec §"Header"). Read from the first
 * bytes of the file; nothing else is parsed.
 * @param {string} file
 * @returns {Promise<string[]>}
 */
export async function carRoots (file) {
  const fh = await fs.promises.open(file, 'r')
  try {
    const { bytesRead, buffer } = await fh.read(Buffer.alloc(64 * 1024), 0, 64 * 1024, 0)
    const head = buffer.subarray(0, bytesRead)
    let len = 0; let shift = 0; let i = 0
    for (;; i++) {
      if (i >= head.length) throw new Error('not a CAR file (no header length)')
      const b = head[i]
      len |= (b & 0x7f) << shift
      if (!(b & 0x80)) { i++; break }
      shift += 7
    }
    if (len <= 0 || i + len > head.length) throw new Error('not a CAR file (header out of range)')
    const header = decodeHeaderCbor(head.subarray(i, i + len))
    if (!header || header.version !== 1 || !Array.isArray(header.roots)) throw new Error('not a CARv1 header')
    return header.roots.map((c) => c.toString())
  } finally {
    await fh.close()
  }
}

/** The CBOR tag IPLD reserves for a CID (dag-cbor spec, "Links"). */
const TAG_CID = 42

/**
 * Decode the CBOR subset a CARv1 header is written in. Throws on anything
 * else — an unparseable header is "not a CAR file", never a guess.
 * @param {Uint8Array} bytes
 */
export function decodeHeaderCbor (bytes) {
  const { value, offset } = readItem(bytes, 0)
  if (offset !== bytes.length) throw new Error('not a CARv1 header (trailing bytes)')
  return value
}

function readItem (b, p) {
  if (p >= b.length) throw new Error('not a CARv1 header (truncated)')
  const major = b[p] >> 5
  const minor = b[p] & 0x1f
  const { value: n, offset } = readLength(b, p, minor)
  switch (major) {
    case 0: // unsigned integer
      return { value: n, offset }
    case 2: { // byte string
      if (offset + n > b.length) throw new Error('not a CARv1 header (truncated bytes)')
      return { value: b.subarray(offset, offset + n), offset: offset + n }
    }
    case 3: { // text string
      if (offset + n > b.length) throw new Error('not a CARv1 header (truncated text)')
      return {
        value: Buffer.from(b.subarray(offset, offset + n)).toString('utf8'),
        offset: offset + n
      }
    }
    case 4: { // array
      const out = []
      let q = offset
      for (let i = 0; i < n; i++) {
        const item = readItem(b, q)
        out.push(item.value)
        q = item.offset
      }
      return { value: out, offset: q }
    }
    case 5: { // map
      const out = {}
      let q = offset
      for (let i = 0; i < n; i++) {
        const key = readItem(b, q)
        if (typeof key.value !== 'string') throw new Error('not a CARv1 header (non-string map key)')
        const val = readItem(b, key.offset)
        out[key.value] = val.value
        q = val.offset
      }
      return { value: out, offset: q }
    }
    case 6: { // tag — only tag 42, a CID, ever appears in this header
      if (n !== TAG_CID) throw new Error(`not a CARv1 header (unexpected CBOR tag ${n})`)
      const inner = readItem(b, offset)
      if (!(inner.value instanceof Uint8Array)) throw new Error('not a CARv1 header (CID tag over a non-byte-string)')
      // A CID in dag-cbor is the identity multibase prefix (0x00) followed by
      // the CID's binary form — dag-cbor spec, "Links".
      if (inner.value.length < 2 || inner.value[0] !== 0x00) throw new Error('not a CARv1 header (CID without its multibase prefix)')
      return { value: CID.decode(inner.value.subarray(1)), offset: inner.offset }
    }
    default:
      throw new Error(`not a CARv1 header (CBOR major type ${major})`)
  }
}

function readLength (b, p, minor) {
  if (minor < 24) return { value: minor, offset: p + 1 }
  if (minor === 24) {
    if (p + 1 >= b.length) throw new Error('not a CARv1 header (truncated length)')
    return { value: b[p + 1], offset: p + 2 }
  }
  if (minor === 25) {
    if (p + 2 >= b.length) throw new Error('not a CARv1 header (truncated length)')
    return { value: (b[p + 1] << 8) | b[p + 2], offset: p + 3 }
  }
  if (minor === 26) {
    if (p + 4 >= b.length) throw new Error('not a CARv1 header (truncated length)')
    return {
      value: ((b[p + 1] << 24) >>> 0) + (b[p + 2] << 16) + (b[p + 3] << 8) + b[p + 4],
      offset: p + 5
    }
  }
  // 27 is an 8-byte length and 31 is the indefinite form. Neither can appear
  // in a CAR header a conforming writer produced, and reading either would
  // mean accepting a header we cannot bound.
  throw new Error(`not a CARv1 header (CBOR additional information ${minor})`)
}
